{
  "ShortName": "/HuaweiMDC/Platform/CanMsgDataType/Element",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "timeStamp",
      "Type": "/HuaweiMDC/Platform/CanMsgDataType/Systemtime"
    },
    {
      "Name": "canId",
      "Type": "/HuaweiMDC/ImplementationDataType/UInt32"
    },
    {
      "Name": "validLen",
      "Type": "/HuaweiMDC/ImplementationDataType/UInt8"
    },
    {
      "Name": "data",
      "Type": "/HuaweiMDC/Platform/CanMsgDataType/CanData"
    }
  ],
  "IsPlane": "false"
}