{
  "ShortName": "/HuaweiMDC/LidarRosTypes/SinglePoint",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "x",
      "Type": "/HuaweiMDC/ImplementationDataType/Float"
    },
    {
      "Name": "y",
      "Type": "/HuaweiMDC/ImplementationDataType/Float"
    },
    {
      "Name": "z",
      "Type": "/HuaweiMDC/ImplementationDataType/Float"
    },
    {
      "Name": "intensity",
      "Type": "/HuaweiMDC/ImplementationDataType/Float"
    },
    {
      "Name": "ring",
      "Type": "/HuaweiMDC/ImplementationDataType/UInt32"
    }
  ],
  "IsPlane": "true"
}