{
  "ShortName": "/jmc_auto/vehicle_signal/VehicleSignal",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "high_beam",
      "Type": "/HuaweiMDC/ImplementationDataType/Bool"
    },
    {
      "Name": "low_beam",
      "Type": "/HuaweiMDC/ImplementationDataType/Bool"
    },
    {
      "Name": "horn",
      "Type": "/HuaweiMDC/ImplementationDataType/Bool"
    },
    {
      "Name": "emergency_light",
      "Type": "/HuaweiMDC/ImplementationDataType/Bool"
    },
    {
      "Name": "turn_signal",
      "Type": "/jmc_auto/vehicle_signal/TurnSignal"
    }
  ],
  "IsPlane": "true"
}