{
  "ShortName": "/jmc_auto/adapters/adapter_config/AdapterConfig",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "type",
      "Type": "/jmc_auto/adapters/adapter_config/MessageType"
    },
    {
      "Name": "mode",
      "Type": "/jmc_auto/adapters/adapter_config/Mode"
    },
    {
      "Name": "message_history_limit",
      "Type": "/HuaweiMDC/ImplementationDataType/Int32"
    },
    {
      "Name": "latch",
      "Type": "/HuaweiMDC/ImplementationDataType/Bool",
      "Padding": "3"
    }
  ],
  "IsPlane": "true"
}