{
  "ShortName": "/jmc_auto/pnc_point/PathPoint",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "x",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "y",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "z",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "theta",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "kappa",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "s",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "dkappa",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "ddkappa",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "lane_id",
      "Type": "/HuaweiMDC/ImplementationDataType/String"
    }
  ],
  "IsPlane": "false"
}