{
  "ShortName": "/jmc_auto/configs/vehicle_config/VehicleConfig",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "header",
      "Type": "/jmc_auto/header/Header"
    },
    {
      "Name": "vehicle_param",
      "Type": "/jmc_auto/configs/vehicle_config/VehicleParam"
    },
    {
      "Name": "extrinsics",
      "Type": "/jmc_auto/configs/vehicle_config/Extrinsics"
    }
  ],
  "IsPlane": "false"
}