{
  "ShortName": "/jmc_auto/Platform/ChassisDateType/WheelSpeedType",
  "Namespace": "::",
  "Type": "ENUMERATION",
  "DataType": "/HuaweiMDC/ImplementationDataType/UInt8",
  "value": [
    {
      "Label": "FORWARD",
      "Value": "0"
    },
    {
      "Label": "BACKWARD",
      "Value": "1"
    },
    {
      "Label": "STANDSTILL",
      "Value": "2"
    },
    {
      "Label": "INVALID",
      "Value": "3"
    }
  ]
}