{
  "ShortName": "/jmc_auto/record/ChannelCache",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "message_number",
      "Type": "/HuaweiMDC/ImplementationDataType/UInt64"
    },
    {
      "Name": "name",
      "Type": "/HuaweiMDC/ImplementationDataType/String"
    },
    {
      "Name": "message_type",
      "Type": "/HuaweiMDC/ImplementationDataType/String"
    },
    {
      "Name": "proto_desc",
      "Type": "/invalid"
    }
  ],
  "IsPlane": "false"
}