{
  "ShortName": "/jmc_auto/pnc_point/SpeedPoint",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "s",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "t",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "v",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "a",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "da",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    }
  ],
  "IsPlane": "true"
}