{
  "ShortName": "/jmc_auto/geometry/jmc_auto/geometry/Polygon/Quaternion",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "qx",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "qy",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "qz",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "qw",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    }
  ],
  "IsPlane": "true"
}