{
  "ShortName": "/jmc_auto/adapters/adapter_config/MessageType",
  "Namespace": "::",
  "Type": "ENUMERATION",
  "DataType": "/HuaweiMDC/ImplementationDataType/UInt16",
  "value": [
    {
      "Label": "POINT_CLOUD",
      "Value": "1"
    },
    {
      "Label": "GPS",
      "Value": "2"
    },
    {
      "Label": "IMU",
      "Value": "3"
    },
    {
      "Label": "CHASSIS",
      "Value": "4"
    },
    {
      "Label": "LOCALIZATION",
      "Value": "5"
    },
    {
      "Label": "PLANNING_TRAJECTORY",
      "Value": "6"
    },
    {
      "Label": "MONITOR",
      "Value": "7"
    },
    {
      "Label": "PAD",
      "Value": "8"
    },
    {
      "Label": "CONTROL_COMMAND",
      "Value": "9"
    },
    {
      "Label": "PREDICTION",
      "Value": "10"
    },
    {
      "Label": "PERCEPTION_OBSTACLES",
      "Value": "11"
    },
    {
      "Label": "TRAFFIC_LIGHT_DETECTION",
      "Value": "12"
    },
    {
      "Label": "CHASSIS_DETAIL",
      "Value": "13"
    },
    {
      "Label": "DECISION",
      "Value": "14"
    },
    {
      "Label": "CANBUS",
      "Value": "15"
    },
    {
      "Label": "ROUTING_REQUEST",
      "Value": "16"
    },
    {
      "Label": "ROUTING_RESPONSE",
      "Value": "17"
    },
    {
      "Label": "RELATIVE_ODOMETRY",
      "Value": "18"
    },
    {
      "Label": "INS_STAT",
      "Value": "19"
    },
    {
      "Label": "HMI_COMMAND",
      "Value": "20"
    },
    {
      "Label": "SYSTEM_STATUS",
      "Value": "21"
    },
    {
      "Label": "INS_STATUS",
      "Value": "22"
    },
    {
      "Label": "GNSS_STATUS",
      "Value": "23"
    },
    {
      "Label": "CONTI_RADAR",
      "Value": "24"
    },
    {
      "Label": "DRIVE_EVENT",
      "Value": "25"
    },
    {
      "Label": "GNSS_RTK_OBS",
      "Value": "26"
    },
    {
      "Label": "GNSS_RTK_EPH",
      "Value": "27"
    },
    {
      "Label": "GNSS_BEST_POSE",
      "Value": "28"
    },
    {
      "Label": "LOCALIZATION_MSF_GNSS",
      "Value": "29"
    },
    {
      "Label": "LOCALIZATION_MSF_LIDAR",
      "Value": "30"
    },
    {
      "Label": "LOCALIZATION_MSF_SINS_PVA",
      "Value": "31"
    },
    {
      "Label": "RAW_IMU",
      "Value": "32"
    },
    {
      "Label": "LOCALIZATION_MSF_STATUS",
      "Value": "33"
    },
    {
      "Label": "STATIC_INFO",
      "Value": "34"
    },
    {
      "Label": "RELATIVE_MAP",
      "Value": "35"
    },
    {
      "Label": "NAVIGATION",
      "Value": "36"
    },
    {
      "Label": "ULTRASONIC_RADAR",
      "Value": "37"
    },
    {
      "Label": "PERCEPTION_LANE_MASK",
      "Value": "38"
    },
    {
      "Label": "GUARDIAN",
      "Value": "39"
    },
    {
      "Label": "GNSS_RAW_DATA",
      "Value": "40"
    },
    {
      "Label": "STREAM_STATUS",
      "Value": "41"
    },
    {
      "Label": "GNSS_HEADING",
      "Value": "42"
    },
    {
      "Label": "RTCM_DATA",
      "Value": "43"
    },
    {
      "Label": "VLP16_POINT_CLOUD",
      "Value": "44"
    },
    {
      "Label": "POINT_CLOUD_RAW",
      "Value": "45"
    },
    {
      "Label": "VELODYNE_RAW",
      "Value": "46"
    },
    {
      "Label": "POINT_CLOUD_FUSION",
      "Value": "47"
    },
    {
      "Label": "REMOTE_CONTROL",
      "Value": "48"
    }
  ]
}