{
  "ShortName": "/jmc_auto/Platform/ChassisDateType/Sonar",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "range",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "translation",
      "Type": "/jmc_auto/geometry/Point3D"
    },
    {
      "Name": "rotation",
      "Type": "/jmc_auto/geometry/Quaternion"
    }
  ],
  "IsPlane": "true"
}