{
  "ShortName": "/jmc_auto/record/ChunkHeaderCache",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "message_number",
      "Type": "/HuaweiMDC/ImplementationDataType/UInt64"
    },
    {
      "Name": "begin_time",
      "Type": "/HuaweiMDC/ImplementationDataType/UInt64"
    },
    {
      "Name": "end_time",
      "Type": "/HuaweiMDC/ImplementationDataType/UInt64"
    },
    {
      "Name": "raw_size",
      "Type": "/HuaweiMDC/ImplementationDataType/UInt64"
    }
  ],
  "IsPlane": "true"
}