{
  "ShortName": "/jmc_auto/configs/vehicle_config/Transform",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "source_frame",
      "Type": "/HuaweiMDC/ImplementationDataType/ByteArray"
    },
    {
      "Name": "target_frame",
      "Type": "/HuaweiMDC/ImplementationDataType/ByteArray"
    },
    {
      "Name": "translation",
      "Type": "/jmc_auto/geometry/Point3D"
    },
    {
      "Name": "rotation",
      "Type": "/jmc_auto/geometry/Quaternion"
    }
  ],
  "IsPlane": "false"
}