{
  "ShortName": "/jmc_auto/configs/vehicle_config/VehicleParam",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "front_edge_to_center",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "back_edge_to_center",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "left_edge_to_center",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "right_edge_to_center",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "length",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "width",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "height",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "min_turn_radius",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "max_acceleration",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "max_deceleration",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "max_steer_angle",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "max_steer_angle_rate",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "min_steer_angle_rate",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "steer_ratio",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "wheel_base",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "wheel_rolling_radius",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "max_abs_speed_when_stopped",
      "Type": "/HuaweiMDC/ImplementationDataType/Float",
      "Padding": "4"
    }
  ],
  "IsPlane": "true"
}