{
  "ShortName": "/jmc_auto/Platform/LocalizationDateType/LocalizationEstimate",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "header",
      "Type": "/jmc_auto/header/Header"
    },
    {
      "Name": "pose",
      "Type": "/jmc_auto/Platform/LocalizationDateType/Pose"
    },
    {
      "Name": "uncertainty",
      "Type": "/jmc_auto/Platform/LocalizationDateType/Uncertainty"
    },
    {
      "Name": "measurement_time",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "trajectory_point",
      "Type": "/jmc_auto/pnc_point/TrajectoryPoint"
    }
  ],
  "IsPlane": "false"
}