{
  "ShortName": "/jmc_auto/Functional/ControlCommandDataType/jmc_auto/Functional/ControlCommandDataType/SimpleLongtitudinalDebug/PadMessage",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "header",
      "Type": "/jmc_auto/header/Header"
    },
    {
      "Name": "action",
      "Type": "/jmc_auto/Functional/ControlCommandDataType/DrivingAction",
      "Padding": "6"
    }
  ],
  "IsPlane": "true"
}