{
  "ShortName": "/jmc_auto/geometry/Point3D",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "x",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "y",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "z",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    }
  ],
  "IsPlane": "true"
}