{
  "ShortName": "/jmc_auto/Modules/ChassisDataType/GpsQuality",
  "Namespace": "::",
  "Type": "ENUMERATION",
  "DataType": "/HuaweiMDC/ImplementationDataType/UInt8",
  "value": [
    {
      "Label": "FIX_NO",
      "Value": "0"
    },
    {
      "Label": "FIX_2D",
      "Value": "1"
    },
    {
      "Label": "FIX_3D",
      "Value": "2"
    },
    {
      "Label": "FIX_INVALID",
      "Value": "3"
    }
  ]
}