{
  "ShortName": "/jmc_auto/Functional/ControlCommandDataType/InputDebug",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "localization_header",
      "Type": "/jmc_auto/header/Header"
    },
    {
      "Name": "canbus_header",
      "Type": "/jmc_auto/header/Header"
    },
    {
      "Name": "trajectory_header",
      "Type": "/jmc_auto/header/Header"
    }
  ],
  "IsPlane": "false"
}