{
  "ShortName": "/jmc_auto/Modules/ControlCommandDataType/SimpleLateralDebug",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "lateral_error",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "ref_heading",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "heading",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "heading_error",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "heading_error_rate",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "lateral_error_rate",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "curvature",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "steer_angle",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "steer_angle_feedforward",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "steer_angle_lateral_contribution",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "steer_angle_lateral_rate_contribution",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "steer_angle_heading_contribution",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "steer_angle_heading_rate_contribution",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "steer_angle_feedback",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "steering_position",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "ref_speed",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "steer_angle_limited",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "steer_targe_position_error",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "steering_torque",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "lateral_acceleration",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "lateral_jerk",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "ref_heading_rate",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "heading_rate",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "ref_heading_acceleration",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "heading_acceleration",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "heading_error_acceleration",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "ref_heading_jerk",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "heading_jerk",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "heading_error_jerk",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "lateral_error_feedback",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "heading_error_feedback",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "steer_angle_feedback_augment",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    }
  ],
  "IsPlane": "true"
}