{
  "ShortName": "/jmc_auto/Modules/ChassisDateType/jmc_auto/Modules/ChassisDateType/Surround/WheelSpeed",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "cross_traffic_alert_left",
      "Type": "/HuaweiMDC/ImplementationDataType/Bool"
    },
    {
      "Name": "cross_traffic_alert_left_enabled",
      "Type": "/HuaweiMDC/ImplementationDataType/Bool",
      "Padding": "6"
    },
    {
      "Name": "blind_spot_left_alert",
      "Type": "/HuaweiMDC/ImplementationDataType/Bool"
    },
    {
      "Name": "blind_spot_left_alert_enabled",
      "Type": "/HuaweiMDC/ImplementationDataType/Bool"
    },
    {
      "Name": "cross_traffic_alert_right",
      "Type": "/HuaweiMDC/ImplementationDataType/Bool",
      "Padding": "6"
    },
    {
      "Name": "cross_traffic_alert_right_enabled",
      "Type": "/HuaweiMDC/ImplementationDataType/Bool"
    },
    {
      "Name": "blind_spot_right_alert",
      "Type": "/HuaweiMDC/ImplementationDataType/Bool"
    },
    {
      "Name": "blind_spot_right_alert_enabled",
      "Type": "/HuaweiMDC/ImplementationDataType/Bool",
      "Padding": "6"
    },
    {
      "Name": "sonar00",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "sonar01",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "sonar02",
      "Type": "/HuaweiMDC/ImplementationDataType/Double",
      "Padding": "6"
    },
    {
      "Name": "sonar03",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "sonar04",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "sonar05",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "sonar06",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "sonar07",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "sonar08",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "sonar09",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "sonar10",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "sonar11",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "sonar_enabled",
      "Type": "/HuaweiMDC/ImplementationDataType/Bool"
    },
    {
      "Name": "sonar_fault",
      "Type": "/HuaweiMDC/ImplementationDataType/Bool",
      "Padding": "6"
    },
    {
      "Name": "is_wheel_spd_rr_valid",
      "Type": "/HuaweiMDC/ImplementationDataType/Bool"
    },
    {
      "Name": "wheel_direction_rr",
      "Type": "/jmc_auto/Modules/ChassisDateType/WheelSpeedType"
    },
    {
      "Name": "wheel_spd_rr",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "is_wheel_spd_rl_valid",
      "Type": "/HuaweiMDC/ImplementationDataType/Bool"
    },
    {
      "Name": "wheel_direction_rl",
      "Type": "/jmc_auto/Modules/ChassisDateType/WheelSpeedType"
    },
    {
      "Name": "wheel_spd_rl",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "is_wheel_spd_fr_valid",
      "Type": "/HuaweiMDC/ImplementationDataType/Bool"
    },
    {
      "Name": "wheel_direction_fr",
      "Type": "/jmc_auto/Modules/ChassisDateType/WheelSpeedType"
    },
    {
      "Name": "wheel_spd_fr",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "is_wheel_spd_fl_valid",
      "Type": "/HuaweiMDC/ImplementationDataType/Bool"
    },
    {
      "Name": "wheel_direction_fl",
      "Type": "/jmc_auto/Modules/ChassisDateType/WheelSpeedType"
    },
    {
      "Name": "wheel_spd_fl",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    }
  ],
  "IsPlane": "true"
}