{
  "ShortName": "/jmc_auto/vehicle_state/vehicle_state/VehicleState",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "x",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "y",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "z",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "timestamp",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "roll",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "pitch",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "yaw",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "heading",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "kappa",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "linear_velocity",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "angular_velocity",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "linear_acceleration",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "gear",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "driving_mode",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "pose",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    }
  ],
  "IsPlane": "true"
}