{
  "ShortName": "/jmc_auto/drive_state/Advice",
  "Namespace": "::",
  "Type": "ENUMERATION",
  "DataType": "/HuaweiMDC/ImplementationDataType/UInt16",
  "value": [
    {
      "Label": "UNKNOW",
      "Value": "0"
    },
    {
      "Label": "DISALLOW_ENGAGE",
      "Value": "1"
    },
    {
      "Label": "READY_TO_ENGAGE",
      "Value": "2"
    },
    {
      "Label": "KEEP_ENGAGE",
      "Value": "3"
    },
    {
      "Label": "PREPARE_DISENGAGE",
      "Value": "4"
    }
  ]
}