{
  "ShortName": "/jmc_auto/Functional/ControlCommandDataType/jmc_auto/Functional/ControlCommandDataType/SimpleLongtitudinalDebug/PadMessage",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "header",
      "Type": "/jmc_auto/header/Header"
    },
    {
      "Name": "driving_mode",
      "Type": "/jmc_auto/Platform/ChassisDateType/DrivingMode"
    },
    {
      "Name": "action",
      "Type": "/jmc_auto/Functional/ControlCommandDataType/DrivingAction"
    }
  ],
  "IsPlane": "false"
}