{
  "ShortName": "/jmc_auto/Functional/ControlCommandDataType/Debug",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "simple_lon_debug",
      "Type": "/jmc_auto/Functional/ControlCommandDataType/SimpleLongtitudinalDebug"
    },
    {
      "Name": "simple_lat_debug",
      "Type": "/jmc_auto/Functional/ControlCommandDataType/SimpleLateralDebug"
    },
    {
      "Name": "input_debug",
      "Type": "/jmc_auto/Functional/ControlCommandDataType/InputDebug"
    }
  ],
  "IsPlane": "false"
}