// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/planning/proto/open_space_pre_stop_decider_config.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "modules/planning/proto/open_space_pre_stop_decider_config.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace jmc_auto {
namespace planning {
class OpenSpacePreStopDeciderConfigDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<OpenSpacePreStopDeciderConfig> {
} _OpenSpacePreStopDeciderConfig_default_instance_;

namespace protobuf_modules_2fplanning_2fproto_2fopen_5fspace_5fpre_5fstop_5fdecider_5fconfig_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] = {
  { NULL, NULL, 0, -1, -1, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OpenSpacePreStopDeciderConfig, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OpenSpacePreStopDeciderConfig, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OpenSpacePreStopDeciderConfig, stop_type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OpenSpacePreStopDeciderConfig, rightaway_stop_distance_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(OpenSpacePreStopDeciderConfig, stop_distance_to_target_),
  0,
  1,
  2,
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, 8, sizeof(OpenSpacePreStopDeciderConfig)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_OpenSpacePreStopDeciderConfig_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "modules/planning/proto/open_space_pre_stop_decider_config.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace

void TableStruct::Shutdown() {
  _OpenSpacePreStopDeciderConfig_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _OpenSpacePreStopDeciderConfig_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\?modules/planning/proto/open_space_pre_"
      "stop_decider_config.proto\022\021jmc_auto.plan"
      "ning\"\210\002\n\035OpenSpacePreStopDeciderConfig\022L"
      "\n\tstop_type\030\001 \001(\01629.jmc_auto.planning.Op"
      "enSpacePreStopDeciderConfig.StopType\022\"\n\027"
      "rightaway_stop_distance\030\002 \001(\001:\0012\022\"\n\027stop"
      "_distance_to_target\030\003 \001(\001:\0015\"Q\n\010StopType"
      "\022\017\n\013NOT_DEFINED\020\000\022\013\n\007PARKING\020\001\022\r\n\tPULL_O"
      "VER\020\002\022\030\n\024NARROW_STREET_U_TURN\020\003"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 351);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "modules/planning/proto/open_space_pre_stop_decider_config.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_modules_2fplanning_2fproto_2fopen_5fspace_5fpre_5fstop_5fdecider_5fconfig_2eproto

const ::google::protobuf::EnumDescriptor* OpenSpacePreStopDeciderConfig_StopType_descriptor() {
  protobuf_modules_2fplanning_2fproto_2fopen_5fspace_5fpre_5fstop_5fdecider_5fconfig_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_modules_2fplanning_2fproto_2fopen_5fspace_5fpre_5fstop_5fdecider_5fconfig_2eproto::file_level_enum_descriptors[0];
}
bool OpenSpacePreStopDeciderConfig_StopType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const OpenSpacePreStopDeciderConfig_StopType OpenSpacePreStopDeciderConfig::NOT_DEFINED;
const OpenSpacePreStopDeciderConfig_StopType OpenSpacePreStopDeciderConfig::PARKING;
const OpenSpacePreStopDeciderConfig_StopType OpenSpacePreStopDeciderConfig::PULL_OVER;
const OpenSpacePreStopDeciderConfig_StopType OpenSpacePreStopDeciderConfig::NARROW_STREET_U_TURN;
const OpenSpacePreStopDeciderConfig_StopType OpenSpacePreStopDeciderConfig::StopType_MIN;
const OpenSpacePreStopDeciderConfig_StopType OpenSpacePreStopDeciderConfig::StopType_MAX;
const int OpenSpacePreStopDeciderConfig::StopType_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int OpenSpacePreStopDeciderConfig::kStopTypeFieldNumber;
const int OpenSpacePreStopDeciderConfig::kRightawayStopDistanceFieldNumber;
const int OpenSpacePreStopDeciderConfig::kStopDistanceToTargetFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

OpenSpacePreStopDeciderConfig::OpenSpacePreStopDeciderConfig()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_modules_2fplanning_2fproto_2fopen_5fspace_5fpre_5fstop_5fdecider_5fconfig_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:jmc_auto.planning.OpenSpacePreStopDeciderConfig)
}
OpenSpacePreStopDeciderConfig::OpenSpacePreStopDeciderConfig(const OpenSpacePreStopDeciderConfig& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&stop_type_, &from.stop_type_,
    reinterpret_cast<char*>(&stop_distance_to_target_) -
    reinterpret_cast<char*>(&stop_type_) + sizeof(stop_distance_to_target_));
  // @@protoc_insertion_point(copy_constructor:jmc_auto.planning.OpenSpacePreStopDeciderConfig)
}

void OpenSpacePreStopDeciderConfig::SharedCtor() {
  _cached_size_ = 0;
  stop_type_ = 0;
  rightaway_stop_distance_ = 2;
  stop_distance_to_target_ = 5;
}

OpenSpacePreStopDeciderConfig::~OpenSpacePreStopDeciderConfig() {
  // @@protoc_insertion_point(destructor:jmc_auto.planning.OpenSpacePreStopDeciderConfig)
  SharedDtor();
}

void OpenSpacePreStopDeciderConfig::SharedDtor() {
}

void OpenSpacePreStopDeciderConfig::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* OpenSpacePreStopDeciderConfig::descriptor() {
  protobuf_modules_2fplanning_2fproto_2fopen_5fspace_5fpre_5fstop_5fdecider_5fconfig_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_modules_2fplanning_2fproto_2fopen_5fspace_5fpre_5fstop_5fdecider_5fconfig_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const OpenSpacePreStopDeciderConfig& OpenSpacePreStopDeciderConfig::default_instance() {
  protobuf_modules_2fplanning_2fproto_2fopen_5fspace_5fpre_5fstop_5fdecider_5fconfig_2eproto::InitDefaults();
  return *internal_default_instance();
}

OpenSpacePreStopDeciderConfig* OpenSpacePreStopDeciderConfig::New(::google::protobuf::Arena* arena) const {
  OpenSpacePreStopDeciderConfig* n = new OpenSpacePreStopDeciderConfig;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void OpenSpacePreStopDeciderConfig::Clear() {
// @@protoc_insertion_point(message_clear_start:jmc_auto.planning.OpenSpacePreStopDeciderConfig)
  if (_has_bits_[0 / 32] & 7u) {
    stop_type_ = 0;
    rightaway_stop_distance_ = 2;
    stop_distance_to_target_ = 5;
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool OpenSpacePreStopDeciderConfig::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:jmc_auto.planning.OpenSpacePreStopDeciderConfig)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .jmc_auto.planning.OpenSpacePreStopDeciderConfig.StopType stop_type = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::jmc_auto::planning::OpenSpacePreStopDeciderConfig_StopType_IsValid(value)) {
            set_stop_type(static_cast< ::jmc_auto::planning::OpenSpacePreStopDeciderConfig_StopType >(value));
          } else {
            mutable_unknown_fields()->AddVarint(1, value);
          }
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional double rightaway_stop_distance = 2 [default = 2];
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(17u)) {
          set_has_rightaway_stop_distance();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &rightaway_stop_distance_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional double stop_distance_to_target = 3 [default = 5];
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(25u)) {
          set_has_stop_distance_to_target();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &stop_distance_to_target_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:jmc_auto.planning.OpenSpacePreStopDeciderConfig)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:jmc_auto.planning.OpenSpacePreStopDeciderConfig)
  return false;
#undef DO_
}

void OpenSpacePreStopDeciderConfig::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:jmc_auto.planning.OpenSpacePreStopDeciderConfig)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional .jmc_auto.planning.OpenSpacePreStopDeciderConfig.StopType stop_type = 1;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->stop_type(), output);
  }

  // optional double rightaway_stop_distance = 2 [default = 2];
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->rightaway_stop_distance(), output);
  }

  // optional double stop_distance_to_target = 3 [default = 5];
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->stop_distance_to_target(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:jmc_auto.planning.OpenSpacePreStopDeciderConfig)
}

::google::protobuf::uint8* OpenSpacePreStopDeciderConfig::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:jmc_auto.planning.OpenSpacePreStopDeciderConfig)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional .jmc_auto.planning.OpenSpacePreStopDeciderConfig.StopType stop_type = 1;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->stop_type(), target);
  }

  // optional double rightaway_stop_distance = 2 [default = 2];
  if (cached_has_bits & 0x00000002u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->rightaway_stop_distance(), target);
  }

  // optional double stop_distance_to_target = 3 [default = 5];
  if (cached_has_bits & 0x00000004u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->stop_distance_to_target(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:jmc_auto.planning.OpenSpacePreStopDeciderConfig)
  return target;
}

size_t OpenSpacePreStopDeciderConfig::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:jmc_auto.planning.OpenSpacePreStopDeciderConfig)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  if (_has_bits_[0 / 32] & 7u) {
    // optional .jmc_auto.planning.OpenSpacePreStopDeciderConfig.StopType stop_type = 1;
    if (has_stop_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->stop_type());
    }

    // optional double rightaway_stop_distance = 2 [default = 2];
    if (has_rightaway_stop_distance()) {
      total_size += 1 + 8;
    }

    // optional double stop_distance_to_target = 3 [default = 5];
    if (has_stop_distance_to_target()) {
      total_size += 1 + 8;
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void OpenSpacePreStopDeciderConfig::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:jmc_auto.planning.OpenSpacePreStopDeciderConfig)
  GOOGLE_DCHECK_NE(&from, this);
  const OpenSpacePreStopDeciderConfig* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const OpenSpacePreStopDeciderConfig>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:jmc_auto.planning.OpenSpacePreStopDeciderConfig)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:jmc_auto.planning.OpenSpacePreStopDeciderConfig)
    MergeFrom(*source);
  }
}

void OpenSpacePreStopDeciderConfig::MergeFrom(const OpenSpacePreStopDeciderConfig& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:jmc_auto.planning.OpenSpacePreStopDeciderConfig)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 7u) {
    if (cached_has_bits & 0x00000001u) {
      stop_type_ = from.stop_type_;
    }
    if (cached_has_bits & 0x00000002u) {
      rightaway_stop_distance_ = from.rightaway_stop_distance_;
    }
    if (cached_has_bits & 0x00000004u) {
      stop_distance_to_target_ = from.stop_distance_to_target_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void OpenSpacePreStopDeciderConfig::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:jmc_auto.planning.OpenSpacePreStopDeciderConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void OpenSpacePreStopDeciderConfig::CopyFrom(const OpenSpacePreStopDeciderConfig& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:jmc_auto.planning.OpenSpacePreStopDeciderConfig)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool OpenSpacePreStopDeciderConfig::IsInitialized() const {
  return true;
}

void OpenSpacePreStopDeciderConfig::Swap(OpenSpacePreStopDeciderConfig* other) {
  if (other == this) return;
  InternalSwap(other);
}
void OpenSpacePreStopDeciderConfig::InternalSwap(OpenSpacePreStopDeciderConfig* other) {
  std::swap(stop_type_, other->stop_type_);
  std::swap(rightaway_stop_distance_, other->rightaway_stop_distance_);
  std::swap(stop_distance_to_target_, other->stop_distance_to_target_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata OpenSpacePreStopDeciderConfig::GetMetadata() const {
  protobuf_modules_2fplanning_2fproto_2fopen_5fspace_5fpre_5fstop_5fdecider_5fconfig_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_modules_2fplanning_2fproto_2fopen_5fspace_5fpre_5fstop_5fdecider_5fconfig_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// OpenSpacePreStopDeciderConfig

// optional .jmc_auto.planning.OpenSpacePreStopDeciderConfig.StopType stop_type = 1;
bool OpenSpacePreStopDeciderConfig::has_stop_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void OpenSpacePreStopDeciderConfig::set_has_stop_type() {
  _has_bits_[0] |= 0x00000001u;
}
void OpenSpacePreStopDeciderConfig::clear_has_stop_type() {
  _has_bits_[0] &= ~0x00000001u;
}
void OpenSpacePreStopDeciderConfig::clear_stop_type() {
  stop_type_ = 0;
  clear_has_stop_type();
}
::jmc_auto::planning::OpenSpacePreStopDeciderConfig_StopType OpenSpacePreStopDeciderConfig::stop_type() const {
  // @@protoc_insertion_point(field_get:jmc_auto.planning.OpenSpacePreStopDeciderConfig.stop_type)
  return static_cast< ::jmc_auto::planning::OpenSpacePreStopDeciderConfig_StopType >(stop_type_);
}
void OpenSpacePreStopDeciderConfig::set_stop_type(::jmc_auto::planning::OpenSpacePreStopDeciderConfig_StopType value) {
  assert(::jmc_auto::planning::OpenSpacePreStopDeciderConfig_StopType_IsValid(value));
  set_has_stop_type();
  stop_type_ = value;
  // @@protoc_insertion_point(field_set:jmc_auto.planning.OpenSpacePreStopDeciderConfig.stop_type)
}

// optional double rightaway_stop_distance = 2 [default = 2];
bool OpenSpacePreStopDeciderConfig::has_rightaway_stop_distance() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void OpenSpacePreStopDeciderConfig::set_has_rightaway_stop_distance() {
  _has_bits_[0] |= 0x00000002u;
}
void OpenSpacePreStopDeciderConfig::clear_has_rightaway_stop_distance() {
  _has_bits_[0] &= ~0x00000002u;
}
void OpenSpacePreStopDeciderConfig::clear_rightaway_stop_distance() {
  rightaway_stop_distance_ = 2;
  clear_has_rightaway_stop_distance();
}
double OpenSpacePreStopDeciderConfig::rightaway_stop_distance() const {
  // @@protoc_insertion_point(field_get:jmc_auto.planning.OpenSpacePreStopDeciderConfig.rightaway_stop_distance)
  return rightaway_stop_distance_;
}
void OpenSpacePreStopDeciderConfig::set_rightaway_stop_distance(double value) {
  set_has_rightaway_stop_distance();
  rightaway_stop_distance_ = value;
  // @@protoc_insertion_point(field_set:jmc_auto.planning.OpenSpacePreStopDeciderConfig.rightaway_stop_distance)
}

// optional double stop_distance_to_target = 3 [default = 5];
bool OpenSpacePreStopDeciderConfig::has_stop_distance_to_target() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void OpenSpacePreStopDeciderConfig::set_has_stop_distance_to_target() {
  _has_bits_[0] |= 0x00000004u;
}
void OpenSpacePreStopDeciderConfig::clear_has_stop_distance_to_target() {
  _has_bits_[0] &= ~0x00000004u;
}
void OpenSpacePreStopDeciderConfig::clear_stop_distance_to_target() {
  stop_distance_to_target_ = 5;
  clear_has_stop_distance_to_target();
}
double OpenSpacePreStopDeciderConfig::stop_distance_to_target() const {
  // @@protoc_insertion_point(field_get:jmc_auto.planning.OpenSpacePreStopDeciderConfig.stop_distance_to_target)
  return stop_distance_to_target_;
}
void OpenSpacePreStopDeciderConfig::set_stop_distance_to_target(double value) {
  set_has_stop_distance_to_target();
  stop_distance_to_target_ = value;
  // @@protoc_insertion_point(field_set:jmc_auto.planning.OpenSpacePreStopDeciderConfig.stop_distance_to_target)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace planning
}  // namespace jmc_auto

// @@protoc_insertion_point(global_scope)
