// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/planning/proto/st_drivable_boundary.proto

#ifndef PROTOBUF_modules_2fplanning_2fproto_2fst_5fdrivable_5fboundary_2eproto__INCLUDED
#define PROTOBUF_modules_2fplanning_2fproto_2fst_5fdrivable_5fboundary_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace jmc_auto {
namespace planning {
class STDrivableBoundary;
class STDrivableBoundaryDefaultTypeInternal;
extern STDrivableBoundaryDefaultTypeInternal _STDrivableBoundary_default_instance_;
class STDrivableBoundaryInstance;
class STDrivableBoundaryInstanceDefaultTypeInternal;
extern STDrivableBoundaryInstanceDefaultTypeInternal _STDrivableBoundaryInstance_default_instance_;
}  // namespace planning
}  // namespace jmc_auto

namespace jmc_auto {
namespace planning {

namespace protobuf_modules_2fplanning_2fproto_2fst_5fdrivable_5fboundary_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_modules_2fplanning_2fproto_2fst_5fdrivable_5fboundary_2eproto

// ===================================================================

class STDrivableBoundaryInstance : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:jmc_auto.planning.STDrivableBoundaryInstance) */ {
 public:
  STDrivableBoundaryInstance();
  virtual ~STDrivableBoundaryInstance();

  STDrivableBoundaryInstance(const STDrivableBoundaryInstance& from);

  inline STDrivableBoundaryInstance& operator=(const STDrivableBoundaryInstance& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const STDrivableBoundaryInstance& default_instance();

  static inline const STDrivableBoundaryInstance* internal_default_instance() {
    return reinterpret_cast<const STDrivableBoundaryInstance*>(
               &_STDrivableBoundaryInstance_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(STDrivableBoundaryInstance* other);

  // implements Message ----------------------------------------------

  inline STDrivableBoundaryInstance* New() const PROTOBUF_FINAL { return New(NULL); }

  STDrivableBoundaryInstance* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const STDrivableBoundaryInstance& from);
  void MergeFrom(const STDrivableBoundaryInstance& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(STDrivableBoundaryInstance* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional double t = 1;
  bool has_t() const;
  void clear_t();
  static const int kTFieldNumber = 1;
  double t() const;
  void set_t(double value);

  // optional double s_lower = 2;
  bool has_s_lower() const;
  void clear_s_lower();
  static const int kSLowerFieldNumber = 2;
  double s_lower() const;
  void set_s_lower(double value);

  // optional double s_upper = 3;
  bool has_s_upper() const;
  void clear_s_upper();
  static const int kSUpperFieldNumber = 3;
  double s_upper() const;
  void set_s_upper(double value);

  // optional double v_obs_lower = 4;
  bool has_v_obs_lower() const;
  void clear_v_obs_lower();
  static const int kVObsLowerFieldNumber = 4;
  double v_obs_lower() const;
  void set_v_obs_lower(double value);

  // optional double v_obs_upper = 5;
  bool has_v_obs_upper() const;
  void clear_v_obs_upper();
  static const int kVObsUpperFieldNumber = 5;
  double v_obs_upper() const;
  void set_v_obs_upper(double value);

  // @@protoc_insertion_point(class_scope:jmc_auto.planning.STDrivableBoundaryInstance)
 private:
  void set_has_t();
  void clear_has_t();
  void set_has_s_lower();
  void clear_has_s_lower();
  void set_has_s_upper();
  void clear_has_s_upper();
  void set_has_v_obs_lower();
  void clear_has_v_obs_lower();
  void set_has_v_obs_upper();
  void clear_has_v_obs_upper();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  double t_;
  double s_lower_;
  double s_upper_;
  double v_obs_lower_;
  double v_obs_upper_;
  friend struct protobuf_modules_2fplanning_2fproto_2fst_5fdrivable_5fboundary_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class STDrivableBoundary : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:jmc_auto.planning.STDrivableBoundary) */ {
 public:
  STDrivableBoundary();
  virtual ~STDrivableBoundary();

  STDrivableBoundary(const STDrivableBoundary& from);

  inline STDrivableBoundary& operator=(const STDrivableBoundary& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const STDrivableBoundary& default_instance();

  static inline const STDrivableBoundary* internal_default_instance() {
    return reinterpret_cast<const STDrivableBoundary*>(
               &_STDrivableBoundary_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(STDrivableBoundary* other);

  // implements Message ----------------------------------------------

  inline STDrivableBoundary* New() const PROTOBUF_FINAL { return New(NULL); }

  STDrivableBoundary* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const STDrivableBoundary& from);
  void MergeFrom(const STDrivableBoundary& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(STDrivableBoundary* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .jmc_auto.planning.STDrivableBoundaryInstance st_boundary = 1;
  int st_boundary_size() const;
  void clear_st_boundary();
  static const int kStBoundaryFieldNumber = 1;
  const ::jmc_auto::planning::STDrivableBoundaryInstance& st_boundary(int index) const;
  ::jmc_auto::planning::STDrivableBoundaryInstance* mutable_st_boundary(int index);
  ::jmc_auto::planning::STDrivableBoundaryInstance* add_st_boundary();
  ::google::protobuf::RepeatedPtrField< ::jmc_auto::planning::STDrivableBoundaryInstance >*
      mutable_st_boundary();
  const ::google::protobuf::RepeatedPtrField< ::jmc_auto::planning::STDrivableBoundaryInstance >&
      st_boundary() const;

  // @@protoc_insertion_point(class_scope:jmc_auto.planning.STDrivableBoundary)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::jmc_auto::planning::STDrivableBoundaryInstance > st_boundary_;
  friend struct protobuf_modules_2fplanning_2fproto_2fst_5fdrivable_5fboundary_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// STDrivableBoundaryInstance

// optional double t = 1;
inline bool STDrivableBoundaryInstance::has_t() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void STDrivableBoundaryInstance::set_has_t() {
  _has_bits_[0] |= 0x00000001u;
}
inline void STDrivableBoundaryInstance::clear_has_t() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void STDrivableBoundaryInstance::clear_t() {
  t_ = 0;
  clear_has_t();
}
inline double STDrivableBoundaryInstance::t() const {
  // @@protoc_insertion_point(field_get:jmc_auto.planning.STDrivableBoundaryInstance.t)
  return t_;
}
inline void STDrivableBoundaryInstance::set_t(double value) {
  set_has_t();
  t_ = value;
  // @@protoc_insertion_point(field_set:jmc_auto.planning.STDrivableBoundaryInstance.t)
}

// optional double s_lower = 2;
inline bool STDrivableBoundaryInstance::has_s_lower() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void STDrivableBoundaryInstance::set_has_s_lower() {
  _has_bits_[0] |= 0x00000002u;
}
inline void STDrivableBoundaryInstance::clear_has_s_lower() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void STDrivableBoundaryInstance::clear_s_lower() {
  s_lower_ = 0;
  clear_has_s_lower();
}
inline double STDrivableBoundaryInstance::s_lower() const {
  // @@protoc_insertion_point(field_get:jmc_auto.planning.STDrivableBoundaryInstance.s_lower)
  return s_lower_;
}
inline void STDrivableBoundaryInstance::set_s_lower(double value) {
  set_has_s_lower();
  s_lower_ = value;
  // @@protoc_insertion_point(field_set:jmc_auto.planning.STDrivableBoundaryInstance.s_lower)
}

// optional double s_upper = 3;
inline bool STDrivableBoundaryInstance::has_s_upper() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void STDrivableBoundaryInstance::set_has_s_upper() {
  _has_bits_[0] |= 0x00000004u;
}
inline void STDrivableBoundaryInstance::clear_has_s_upper() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void STDrivableBoundaryInstance::clear_s_upper() {
  s_upper_ = 0;
  clear_has_s_upper();
}
inline double STDrivableBoundaryInstance::s_upper() const {
  // @@protoc_insertion_point(field_get:jmc_auto.planning.STDrivableBoundaryInstance.s_upper)
  return s_upper_;
}
inline void STDrivableBoundaryInstance::set_s_upper(double value) {
  set_has_s_upper();
  s_upper_ = value;
  // @@protoc_insertion_point(field_set:jmc_auto.planning.STDrivableBoundaryInstance.s_upper)
}

// optional double v_obs_lower = 4;
inline bool STDrivableBoundaryInstance::has_v_obs_lower() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void STDrivableBoundaryInstance::set_has_v_obs_lower() {
  _has_bits_[0] |= 0x00000008u;
}
inline void STDrivableBoundaryInstance::clear_has_v_obs_lower() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void STDrivableBoundaryInstance::clear_v_obs_lower() {
  v_obs_lower_ = 0;
  clear_has_v_obs_lower();
}
inline double STDrivableBoundaryInstance::v_obs_lower() const {
  // @@protoc_insertion_point(field_get:jmc_auto.planning.STDrivableBoundaryInstance.v_obs_lower)
  return v_obs_lower_;
}
inline void STDrivableBoundaryInstance::set_v_obs_lower(double value) {
  set_has_v_obs_lower();
  v_obs_lower_ = value;
  // @@protoc_insertion_point(field_set:jmc_auto.planning.STDrivableBoundaryInstance.v_obs_lower)
}

// optional double v_obs_upper = 5;
inline bool STDrivableBoundaryInstance::has_v_obs_upper() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void STDrivableBoundaryInstance::set_has_v_obs_upper() {
  _has_bits_[0] |= 0x00000010u;
}
inline void STDrivableBoundaryInstance::clear_has_v_obs_upper() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void STDrivableBoundaryInstance::clear_v_obs_upper() {
  v_obs_upper_ = 0;
  clear_has_v_obs_upper();
}
inline double STDrivableBoundaryInstance::v_obs_upper() const {
  // @@protoc_insertion_point(field_get:jmc_auto.planning.STDrivableBoundaryInstance.v_obs_upper)
  return v_obs_upper_;
}
inline void STDrivableBoundaryInstance::set_v_obs_upper(double value) {
  set_has_v_obs_upper();
  v_obs_upper_ = value;
  // @@protoc_insertion_point(field_set:jmc_auto.planning.STDrivableBoundaryInstance.v_obs_upper)
}

// -------------------------------------------------------------------

// STDrivableBoundary

// repeated .jmc_auto.planning.STDrivableBoundaryInstance st_boundary = 1;
inline int STDrivableBoundary::st_boundary_size() const {
  return st_boundary_.size();
}
inline void STDrivableBoundary::clear_st_boundary() {
  st_boundary_.Clear();
}
inline const ::jmc_auto::planning::STDrivableBoundaryInstance& STDrivableBoundary::st_boundary(int index) const {
  // @@protoc_insertion_point(field_get:jmc_auto.planning.STDrivableBoundary.st_boundary)
  return st_boundary_.Get(index);
}
inline ::jmc_auto::planning::STDrivableBoundaryInstance* STDrivableBoundary::mutable_st_boundary(int index) {
  // @@protoc_insertion_point(field_mutable:jmc_auto.planning.STDrivableBoundary.st_boundary)
  return st_boundary_.Mutable(index);
}
inline ::jmc_auto::planning::STDrivableBoundaryInstance* STDrivableBoundary::add_st_boundary() {
  // @@protoc_insertion_point(field_add:jmc_auto.planning.STDrivableBoundary.st_boundary)
  return st_boundary_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::jmc_auto::planning::STDrivableBoundaryInstance >*
STDrivableBoundary::mutable_st_boundary() {
  // @@protoc_insertion_point(field_mutable_list:jmc_auto.planning.STDrivableBoundary.st_boundary)
  return &st_boundary_;
}
inline const ::google::protobuf::RepeatedPtrField< ::jmc_auto::planning::STDrivableBoundaryInstance >&
STDrivableBoundary::st_boundary() const {
  // @@protoc_insertion_point(field_list:jmc_auto.planning.STDrivableBoundary.st_boundary)
  return st_boundary_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace planning
}  // namespace jmc_auto

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_modules_2fplanning_2fproto_2fst_5fdrivable_5fboundary_2eproto__INCLUDED
