{
  "ShortName": "/jmc_auto/geometry/PointLLH",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "lon",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "lat",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "height",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    }
  ],
  "IsPlane": "true"
}