{
  "ShortName": "/jmc_auto/pnc_point/GaussianInfo",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "sigma_x",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "sigma_y",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "correlation",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "area_probability",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "ellipse_a",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "ellipse_b",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "theta_a",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    }
  ],
  "IsPlane": "true"
}