{
  "ShortName": "/jmc_auto/Platform/LocalizationDateType/Pose",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "position",
      "Type": "/jmc_auto/geometry/PointENU"
    },
    {
      "Name": "orientation",
      "Type": "/jmc_auto/geometry/Quaternion"
    },
    {
      "Name": "linear_velocity",
      "Type": "/jmc_auto/geometry/Point3D"
    },
    {
      "Name": "linear_acceleration",
      "Type": "/jmc_auto/geometry/Point3D"
    },
    {
      "Name": "angular_velocity",
      "Type": "/jmc_auto/geometry/Point3D"
    },
    {
      "Name": "heading",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "linear_acceleration_vrf",
      "Type": "/jmc_auto/geometry/Point3D"
    },
    {
      "Name": "angular_velocity_vrf",
      "Type": "/jmc_auto/geometry/Point3D"
    },
    {
      "Name": "euler_angles",
      "Type": "/jmc_auto/geometry/Point3D"
    }
  ],
  "IsPlane": "true"
}