{
  "ShortName": "/jmc_auto/pnc_point/FrenetFramePoint",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "s",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "l",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "dl",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "ddl",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    }
  ],
  "IsPlane": "true"
}