{
  "ShortName": "/jmc_auto/monitor_log/monitor_log/MonitorMessageItem",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "source",
      "Type": "/jmc_auto/monitor_log/monitor_log/MessageSource"
    },
    {
      "Name": "msg",
      "Type": "/HuaweiMDC/ImplementationDataType/String"
    },
    {
      "Name": "log_level",
      "Type": "/jmc_auto/monitor_log/monitor_log/LogLevel"
    }
  ],
  "IsPlane": "false"
}