{
  "ShortName": "/jmc_auto/Platform/ChassisDateType/BrkPedalStasus",
  "Namespace": "::",
  "Type": "ENUMERATION",
  "DataType": "/HuaweiMDC/ImplementationDataType/UInt8",
  "value": [
    {
      "Label": "NOT_PRESSED",
      "Value": "0"
    },
    {
      "Label": "PRESSED",
      "Value": "1"
    },
    {
      "Label": "RESERRVED",
      "Value": "2"
    },
    {
      "Label": "ERROR",
      "Value": "3"
    }
  ]
}