{
  "ShortName": "/jmc_auto/Modules/ChassisDataType/DrivingMode",
  "Namespace": "::",
  "Type": "ENUMERATION",
  "DataType": "/HuaweiMDC/ImplementationDataType/UInt8",
  "value": [
    {
      "Label": "COMPLETE_MANUAL",
      "Value": "0"
    },
    {
      "Label": "COMPLETE_AUTO_DRIVE",
      "Value": "1"
    },
    {
      "Label": "AUTO_STEER_ONLY",
      "Value": "2"
    },
    {
      "Label": "AUTO_SPEED_ONLY",
      "Value": "3"
    },
    {
      "Label": "EMERGENCY_MODE",
      "Value": "4"
    },
    {
      "Label": "REMOTE_MODE",
      "Value": "5"
    },
    {
      "Label": "APA_MODE",
      "Value": "6"
    }
  ]
}