{
  "ShortName": "/jmc_auto/Modules/ChassisDataType/INS_GpsFlag",
  "Namespace": "::",
  "Type": "ENUMERATION",
  "DataType": "/HuaweiMDC/ImplementationDataType/UInt8",
  "value": [
    {
      "Label": "NONE",
      "Value": "0"
    },
    {
      "Label": "FIXEDPOS",
      "Value": "1"
    },
    {
      "Label": "FIXEDHEIGHT",
      "Value": "2"
    },
    {
      "Label": "DOPPLER_VELOCITY",
      "Value": "8"
    },
    {
      "Label": "SINGLE",
      "Value": "16"
    },
    {
      "Label": "PSRDIFF",
      "Value": "17"
    },
    {
      "Label": "SBAS",
      "Value": "18"
    },
    {
      "Label": "L1_FLOAT",
      "Value": "32"
    },
    {
      "Label": "IONOFREE_FLOAT",
      "Value": "33"
    },
    {
      "Label": "NARROW_FLOAT",
      "Value": "34"
    },
    {
      "Label": "L1_INT",
      "Value": "48"
    },
    {
      "Label": "WIDE_INT",
      "Value": "49"
    },
    {
      "Label": "NARROW_INT",
      "Value": "50"
    }
  ]
}