{
  "ShortName": "/jmc_auto/vehicle_model/vehicle_model_config/VehicleModelConfig",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "model_type",
      "Type": "/jmc_auto/vehicle_model/vehicle_model_config/ModelType",
      "Padding": "4"
    },
    {
      "Name": "rc_kinematic_bicycle_model",
      "Type": "/jmc_auto/vehicle_model/vehicle_model_config/RearCenteredKinematicBicycleModelConfig"
    },
    {
      "Name": "comc_dynamic_bicycle_model",
      "Type": "/jmc_auto/vehicle_model/vehicle_model_config/ComCenteredDynamicBicycleModelConfig"
    },
    {
      "Name": "mlp_model",
      "Type": "/jmc_auto/vehicle_model/vehicle_model_config/MlpModelConfig"
    }
  ],
  "IsPlane": "true"
}