{
  "ShortName": "/jmc_auto/Modules/ControlCommandDataType/jmc_auto/Modules/LocalizationDataType/jmc_auto/Modules/LocalizationDataType/jmc_auto/Modules/LocalizationDataType/Localization/Uncertainty/Pose/ControlCommand",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "header",
      "Type": "/invalid"
    },
    {
      "Name": "pose",
      "Type": "/jmc_auto/Modules/LocalizationDataType/Pose"
    },
    {
      "Name": "uncertainty",
      "Type": "/jmc_auto/Modules/LocalizationDataType/Uncertainty"
    },
    {
      "Name": "measurement_time",
      "Type": "/invalid"
    },
    {
      "Name": "trajectory_point",
      "Type": "/invalid"
    },
    {
      "Name": "position_std_dev",
      "Type": "/invalid"
    },
    {
      "Name": "orientation_std_dev",
      "Type": "/invalid"
    },
    {
      "Name": "linear_velocity_std_dev",
      "Type": "/invalid"
    },
    {
      "Name": "linear_acceleration_std_dev",
      "Type": "/invalid"
    },
    {
      "Name": "angular_velocity_std_dev",
      "Type": "/invalid"
    },
    {
      "Name": "position",
      "Type": "/invalid"
    },
    {
      "Name": "orientation",
      "Type": "/invalid"
    },
    {
      "Name": "linear_velocity",
      "Type": "/invalid"
    },
    {
      "Name": "linear_acceleration",
      "Type": "/invalid"
    },
    {
      "Name": "angular_velocity",
      "Type": "/invalid"
    },
    {
      "Name": "heading",
      "Type": "/invalid"
    },
    {
      "Name": "linear_acceleration_vrf",
      "Type": "/invalid"
    },
    {
      "Name": "angular_velocity_vrf",
      "Type": "/invalid"
    },
    {
      "Name": "euler_angles",
      "Type": "/invalid"
    },
    {
      "Name": "header",
      "Type": "/jmc_auto/header/Header"
    },
    {
      "Name": "throttle",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "brake",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "steering_rate",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "steering_target",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "speed",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "acceleration",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "left_turn",
      "Type": "/HuaweiMDC/ImplementationDataType/Bool"
    },
    {
      "Name": "right_turn",
      "Type": "/HuaweiMDC/ImplementationDataType/Bool"
    },
    {
      "Name": "high_beam",
      "Type": "/HuaweiMDC/ImplementationDataType/Bool"
    },
    {
      "Name": "low_beam",
      "Type": "/HuaweiMDC/ImplementationDataType/Bool"
    },
    {
      "Name": "horn",
      "Type": "/HuaweiMDC/ImplementationDataType/Bool"
    },
    {
      "Name": "turnsignal",
      "Type": "/jmc_auto/vehicle_signal/TurnSignal"
    },
    {
      "Name": "reset_model",
      "Type": "/HuaweiMDC/ImplementationDataType/Bool"
    },
    {
      "Name": "engine_on_off",
      "Type": "/HuaweiMDC/ImplementationDataType/Bool"
    },
    {
      "Name": "trajectory_fraction",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "driving_mode",
      "Type": "/jmc_auto/Modules/ChassisDataType/DrivingMode"
    },
    {
      "Name": "gear_location",
      "Type": "/jmc_auto/Modules/ChassisDataType/GearPosition"
    },
    {
      "Name": "debug",
      "Type": "/jmc_auto/Modules/ControlCommandDataType/Debug"
    },
    {
      "Name": "signal",
      "Type": "/jmc_auto/vehicle_signal/VehicleSignal"
    },
    {
      "Name": "latency_stats",
      "Type": "/jmc_auto/Modules/ControlCommandDataType/LatencyStats"
    },
    {
      "Name": "pad_msg",
      "Type": "/jmc_auto/Modules/ControlCommandDataType/PadMessage"
    },
    {
      "Name": "engage_advice",
      "Type": "/jmc_auto/drive_state/EngageAdvice"
    },
    {
      "Name": "is_in_safe_mode",
      "Type": "/HuaweiMDC/ImplementationDataType/Bool"
    },
    {
      "Name": "steering_torque",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "pam_esp_stop_distance",
      "Type": "/HuaweiMDC/ImplementationDataType/Int32"
    },
    {
      "Name": "ACC_StandstillReq",
      "Type": "/HuaweiMDC/ImplementationDataType/Bool"
    },
    {
      "Name": "steering_angle",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "parking_brake",
      "Type": "/HuaweiMDC/ImplementationDataType/Bool"
    },
    {
      "Name": "PAM_ESP_Target_Gear_Request",
      "Type": "/HuaweiMDC/ImplementationDataType/Int32"
    }
  ],
  "IsPlane": "false"
}