{
  "ShortName": "/HuaweiMDC/CommonDataTypes/Header",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "seq",
      "Type": "/HuaweiMDC/ImplementationDataType/UInt32"
    },
    {
      "Name": "stamp",
      "Type": "/HuaweiMDC/CommonDataTypes/Time"
    },
    {
      "Name": "frameId",
      "Type": "/HuaweiMDC/ImplementationDataType/String"
    }
  ],
  "IsPlane": "false"
}