{
  "ShortName": "/jmc_auto/Modules/ChassisDataType/ChassisErrorCode",
  "Namespace": "::",
  "Type": "ENUMERATION",
  "DataType": "/HuaweiMDC/ImplementationDataType/UInt8",
  "value": [
    {
      "Label": "NO_ERROR",
      "Value": "0"
    },
    {
      "Label": "CMD_NOT_IN_PERIOD",
      "Value": "1"
    },
    {
      "Label": "CHASSIS_ERROR",
      "Value": "2"
    },
    {
      "Label": "MANUAL_INTERVENTION",
      "Value": "3"
    },
    {
      "Label": "CHASSIS_CAN_NOT_IN_PERIOD",
      "Value": "4"
    },
    {
      "Label": "UNKNOWN_ERROR",
      "Value": "5"
    }
  ]
}