{
  "ShortName": "/jmc_auto/Modules/ControlCommandDataType/SimpleLongtitudinalDebug",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "total_time_ms",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "controller_time_ms",
      "Type": "/HuaweiMDC/ImplementationDataType/Double"
    },
    {
      "Name": "total_time_exceeded",
      "Type": "/HuaweiMDC/ImplementationDataType/Bool",
      "Padding": "7"
    }
  ],
  "IsPlane": "true"
}