{
  "ShortName": "/jmc_auto/Modules/ControlCommandDataType/jmc_auto/Modules/ControlCommandDataType/Debug/InputDebug",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "simple_lon_debug",
      "Type": "/jmc_auto/Modules/ControlCommandDataType/SimpleLongtitudinalDebug"
    },
    {
      "Name": "simple_lat_debug",
      "Type": "/jmc_auto/Modules/ControlCommandDataType/SimpleLateralDebug"
    },
    {
      "Name": "input_debug",
      "Type": "/jmc_auto/Modules/ControlCommandDataType/InputDebug"
    },
    {
      "Name": "localization_header",
      "Type": "/jmc_auto/header/Header"
    },
    {
      "Name": "canbus_header",
      "Type": "/jmc_auto/header/Header"
    },
    {
      "Name": "trajectory_header",
      "Type": "/jmc_auto/header/Header"
    }
  ],
  "IsPlane": "true"
}