{
  "ShortName": "/jmc_auto/Modules/ChassisDateType/GearPosition",
  "Namespace": "::",
  "Type": "ENUMERATION",
  "DataType": "/HuaweiMDC/ImplementationDataType/UInt8",
  "value": [
    {
      "Label": "GEAR_NEUTRAL",
      "Value": "0"
    },
    {
      "Label": "GEAR_DRIVE",
      "Value": "1"
    },
    {
      "Label": "GEAR_REVERSE",
      "Value": "2"
    },
    {
      "Label": "GEAR_PARKING",
      "Value": "3"
    },
    {
      "Label": "GEAR_LOW",
      "Value": "4"
    },
    {
      "Label": "GEAR_INVALID",
      "Value": "5"
    },
    {
      "Label": "GEAR_NONE",
      "Value": "6"
    }
  ]
}