{
  "ShortName": "/jmc_auto/Platform/LocalizationDateType/Uncertainty",
  "Namespace": "::",
  "Type": "STRUCTURE",
  "Subelements": [
    {
      "Name": "position_std_dev",
      "Type": "/jmc_auto/geometry/Point3D"
    },
    {
      "Name": "orientation_std_dev",
      "Type": "/jmc_auto/geometry/Point3D"
    },
    {
      "Name": "linear_velocity_std_dev",
      "Type": "/jmc_auto/geometry/Point3D"
    },
    {
      "Name": "linear_acceleration_std_dev",
      "Type": "/jmc_auto/geometry/Point3D"
    },
    {
      "Name": "angular_velocity_std_dev",
      "Type": "/jmc_auto/geometry/Point3D"
    }
  ],
  "IsPlane": "true"
}